type Mutation {
  createUser(data: CreateUserInput!): AuthPayload!
  signinUser(data: SignInUserInput!): AuthPayload!
  updateUser(data: UpdateUserInput!): User!
}

type Query {
  getUsers: [User]!
  getCurrentUser: User!
}

type User {
  uuid: ID!
  email: String!
  username: String!
  password: String!
  stories: [Story]!
  created_at: DateTime!
  updated_at: DateTime!
}

type AuthPayload {
  token: String!
  user: User!
}

input CreateUserInput {
  email: String!
  username: String!
  password: String!
}

input UpdateUserInput {
  email: String
  username: String
  password: String
}

input SignInUserInput {
  email: String!
  password: String!
}
