type Mutation {
  createStory(data: CreateStoryInput): Story!
  updateStory(data: UpdateStoryInput): Story!
}

type Query {
  stories: [Story]!
}

type Story {
  id: ID!
  title: String!
  user: User
  created_at: DateTime!
  updated_at: DateTime!
}

input CreateStoryInput {
  title: String!
  userId: Int!
}

input UpdateStoryInput {
  id: ID!
  title: String!
  userId: Int!
}
