type Mutation {
  createStory(data: CreateStoryInput): Story!
  updateStory(data: UpdateStoryInput): Story!
  deleteStory(uuid: ID!): Story!
}

type Query {
  getStories: [Story]!
}

type Story {
  uuid: ID!
  title: String!
  user: User!
  created_at: DateTime!
  updated_at: DateTime!
}

input CreateStoryInput {
  title: String!
}

input UpdateStoryInput {
  uuid: ID!
  title: String!
}
